### ISSUE TITLE
AttributeError: 'function' object has no attribute

### ISSUE THREAD

**Issue by andrexsaddler** [josephsookim/thespikeggapi#1]
```
AttributeError: 'function' object has no attribute 'get_rankings'
```

```
AttributeError: 'function' object has no attribute 'get_rankings'
```

**Comment by josephsookim** [comment]
Hey! Can you provide some more context on how you reached an AttributeError? Thanks in advance!

**Comment by andrexsaddler** [comment]
> Hey! Can you provide some more context on how you reached an AttributeError? Thanks in advance!

since you're using flask, it should be able to run via web interface so i did this:

```
if __name__ == "__main__":
      app.run(
      host="0.0.0.0",
      port=9271
  )
```

**Comment by josephsookim** [comment]
After adding gunicorn and a Procfile, I'm able to host it on Heroku. Can you try again?

I will also add the link to the hosted api in the readme file soon, so you can check that out if you want.

**Comment by andrexsaddler** [comment]
> After adding gunicorn and a Procfile, I'm able to host it on Heroku. Can you try again?
> 
> I will also add the link to the hosted api in the readme file soon, so you can check that out if you want.

all good now!
